# bitQobo docker image
# use it via running `docker compose up --build`
services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8080:80"
  php:
    restart: always
    volumes:
      - ./docker/php/php.ini:/opt/bitnami/php/lib/php.ini
      - ./:/var/www/html
    build: ./
  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080"
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=sb
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=example
    ports:
      - "4000:3306"
    volumes:
      - ./docker/mariadb-data:/var/lib/mysql
  composer:
    image: composer
    command: composer update --working-dir /var/www/html && composer dump-autoload
    volumes:
      - ./:/var/www/html
